name: test

on: push

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: cmake -E make_directory $GITHUB_WORKSPACE/build
      - run: cd $GITHUB_WORKSPACE/build
      - run: cmake .
      - run: cmake --build .
